services:
  database:
    image: 'postgres:14-alpine'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=password'
      - "SPRING_PROFILES_ACTIVE=local"